/* Generated by tools/sync-workspaces.mjs - do not edit by hand.
   The real wheel: Main (7), Streaming (3), Build (8). */
window.ROVYL = {
  "look": {
    "hoverColor": "#FFFFFF",
    "menuRadius": 140,
    "iconSize": 64,
    "appSpacing": 10,
    "backdropOpacity": 0.9,
    "selectionMode": "area",
    "showLabels": true,
    "globalShortcut": "Alt+F",
    "activationThreshold": 45,
    "radialMonitor": "cursor",
    "mouseTrigger": false,
    "mouseButton": "middle",
    "mouseMode": "click",
    "theme": "black",
    "version": "1.13.0",
    "switchMode": "picker",
    "activeWorkspace": 0,
    "centerLabel": "Center",
    "handsFree": false,
    "handsFreeSensitivity": "low",
    "handsFreeDwellMs": 400
  },
  "workspaces": [
    {
      "name": "Main",
      "key": 1,
      "color": "#3B82F6",
      "paused": false,
      "glyph": [
        {
          "tag": "rect",
          "attrs": {
            "x": "2",
            "y": "4",
            "width": "20",
            "height": "16",
            "rx": "2"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M10 4v4"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M2 8h20"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M6 4v4"
          }
        }
      ],
      "items": [
        {
          "label": "Google",
          "icon": "assets/icons/google.png",
          "glyph": "Globe"
        },
        {
          "label": "Visual Studio Code",
          "icon": "assets/icons/visual-studio-code.png",
          "glyph": "Circle"
        },
        {
          "label": "Discord",
          "icon": "assets/icons/discord.png",
          "glyph": "Circle"
        },
        {
          "label": "Telegram",
          "icon": "assets/icons/telegram.png",
          "glyph": "Circle"
        },
        {
          "label": "WhatsApp",
          "icon": "assets/icons/whatsapp.png",
          "glyph": "Circle"
        },
        {
          "label": "Steam",
          "icon": "assets/icons/steam.png",
          "glyph": "AppWindow"
        },
        {
          "label": "Notion",
          "icon": "assets/icons/notion.png",
          "glyph": "AppWindow"
        }
      ]
    },
    {
      "name": "Streaming",
      "key": 2,
      "color": "#EF4444",
      "paused": false,
      "glyph": [
        {
          "tag": "path",
          "attrs": {
            "d": "m10 7 5 3-5 3Z"
          }
        },
        {
          "tag": "rect",
          "attrs": {
            "width": "20",
            "height": "14",
            "x": "2",
            "y": "3",
            "rx": "2"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M12 17v4"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M8 21h8"
          }
        }
      ],
      "items": [
        {
          "label": "YouTube",
          "icon": "assets/icons/youtube.png",
          "glyph": "Globe"
        },
        {
          "label": "Twitch",
          "icon": "assets/icons/twitch.png",
          "glyph": "Globe"
        },
        {
          "label": "Netflix",
          "icon": "assets/icons/netflix.png",
          "glyph": "Globe"
        }
      ]
    },
    {
      "name": "Build",
      "key": 3,
      "color": "#FFFFFF",
      "paused": false,
      "glyph": [
        {
          "tag": "path",
          "attrs": {
            "d": "m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M5 3v4"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M19 17v4"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M3 5h4"
          }
        },
        {
          "tag": "path",
          "attrs": {
            "d": "M17 19h4"
          }
        }
      ],
      "items": [
        {
          "label": "Claude",
          "icon": "assets/icons/claude.png",
          "glyph": "AppWindow"
        },
        {
          "label": "ChatGPT",
          "icon": "assets/icons/chatgpt.png",
          "glyph": "Globe"
        },
        {
          "label": "Gemini",
          "icon": "assets/icons/gemini.png",
          "glyph": "Globe"
        },
        {
          "label": "Cursor",
          "icon": "assets/icons/cursor.png",
          "glyph": "AppWindow"
        },
        {
          "label": "Antigravity",
          "icon": "assets/icons/antigravity.png",
          "glyph": "AppWindow"
        },
        {
          "label": "Visual Studio Code",
          "icon": "assets/icons/visual-studio-code.png",
          "glyph": "AppWindow"
        },
        {
          "label": "Comet",
          "icon": "assets/icons/comet.png",
          "glyph": "AppWindow"
        },
        {
          "label": "Figma",
          "icon": "assets/icons/figma.png",
          "glyph": "AppWindow"
        }
      ]
    }
  ]
};
